export const countriesWithFlags = [
  { name: "Egypt", code: "+20", flag: "EG", iso: "EG" },
  { name: "United States", code: "+1", flag: "US", iso: "US" },
  { name: "Canada", code: "+1", flag: "CA", iso: "CA" },
  { name: "United Kingdom", code: "+44", flag: "GB", iso: "GB" },
  { name: "France", code: "+33", flag: "FR", iso: "FR" },
  { name: "Germany", code: "+49", flag: "DE", iso: "DE" },
  { name: "Italy", code: "+39", flag: "IT", iso: "IT" },
  { name: "Spain", code: "+34", flag: "ES", iso: "ES" },
  { name: "Netherlands", code: "+31", flag: "NL", iso: "NL" },
  { name: "Belgium", code: "+32", flag: "BE", iso: "BE" },
  { name: "Switzerland", code: "+41", flag: "CH", iso: "CH" },
  { name: "Austria", code: "+43", flag: "AT", iso: "AT" },
  { name: "Denmark", code: "+45", flag: "DK", iso: "DK" },
  { name: "Sweden", code: "+46", flag: "SE", iso: "SE" },
  { name: "Norway", code: "+47", flag: "NO", iso: "NO" },
  { name: "Finland", code: "+358", flag: "FI", iso: "FI" },
  { name: "Poland", code: "+48", flag: "PL", iso: "PL" },
  { name: "Czech Republic", code: "+420", flag: "CZ", iso: "CZ" },
  { name: "Slovakia", code: "+421", flag: "SK", iso: "SK" },
  { name: "Hungary", code: "+36", flag: "HU", iso: "HU" },
  { name: "Romania", code: "+40", flag: "RO", iso: "RO" },
  { name: "Bulgaria", code: "+359", flag: "BG", iso: "BG" },
  { name: "Greece", code: "+30", flag: "GR", iso: "GR" },
  { name: "Portugal", code: "+351", flag: "PT", iso: "PT" },
  { name: "Ireland", code: "+353", flag: "IE", iso: "IE" },
  { name: "Russia", code: "+7", flag: "RU", iso: "RU" },
  { name: "China", code: "+86", flag: "CN", iso: "CN" },
  { name: "Japan", code: "+81", flag: "JP", iso: "JP" },
  { name: "South Korea", code: "+82", flag: "KR", iso: "KR" },
  { name: "India", code: "+91", flag: "IN", iso: "IN" },
  { name: "Pakistan", code: "+92", flag: "PK", iso: "PK" },
  { name: "Bangladesh", code: "+880", flag: "BD", iso: "BD" },
  { name: "Sri Lanka", code: "+94", flag: "LK", iso: "LK" },
  { name: "Malaysia", code: "+60", flag: "MY", iso: "MY" },
  { name: "Singapore", code: "+65", flag: "SG", iso: "SG" },
  { name: "Thailand", code: "+66", flag: "TH", iso: "TH" },
  { name: "Vietnam", code: "+84", flag: "VN", iso: "VN" },
  { name: "Philippines", code: "+63", flag: "PH", iso: "PH" },
  { name: "Indonesia", code: "+62", flag: "ID", iso: "ID" },
  { name: "Australia", code: "+61", flag: "AU", iso: "AU" },
    { name: "New Zealand", code: "+64", flag: "NZ", iso: "NZ" },
  { name: "South Africa", code: "+27", flag: "ZA", iso: "ZA" },
  { name: "Nigeria", code: "+234", flag: "NG", iso: "NG" },
  { name: "Kenya", code: "+254", flag: "KE", iso: "KE" },
  { name: "Ghana", code: "+233", flag: "GH", iso: "GH" },
  { name: "Morocco", code: "+212", flag: "MA", iso: "MA" },
  { name: "Algeria", code: "+213", flag: "DZ", iso: "DZ" },
  { name: "Tunisia", code: "+216", flag: "TN", iso: "TN" },
  { name: "Libya", code: "+218", flag: "LY", iso: "LY" },
  { name: "Sudan", code: "+249", flag: "SD", iso: "SD" },
  { name: "Ethiopia", code: "+251", flag: "ET", iso: "ET" },
  { name: "Uganda", code: "+256", flag: "UG", iso: "UG" },
  { name: "Tanzania", code: "+255", flag: "TZ", iso: "TZ" },
  { name: "Zambia", code: "+260", flag: "ZM", iso: "ZM" },
  { name: "Zimbabwe", code: "+263", flag: "ZW", iso: "ZW" },
  { name: "Botswana", code: "+267", flag: "BW", iso: "BW" },
  { name: "Namibia", code: "+264", flag: "NA", iso: "NA" },
  { name: "Argentina", code: "+54", flag: "AR", iso: "AR" },
  { name: "Brazil", code: "+55", flag: "BR", iso: "BR" },
  { name: "Chile", code: "+56", flag: "CL", iso: "CL" },
  { name: "Colombia", code: "+57", flag: "CO", iso: "CO" },
  { name: "Venezuela", code: "+58", flag: "VE", iso: "VE" },
  { name: "Peru", code: "+51", flag: "PE", iso: "PE" },
  { name: "Ecuador", code: "+593", flag: "EC", iso: "EC" },
  { name: "Bolivia", code: "+591", flag: "BO", iso: "BO" },
  { name: "Paraguay", code: "+595", flag: "PY", iso: "PY" },
  { name: "Uruguay", code: "+598", flag: "UY", iso: "UY" },
  { name: "Mexico", code: "+52", flag: "MX", iso: "MX" },
  { name: "Guatemala", code: "+502", flag: "GT", iso: "GT" },
  { name: "El Salvador", code: "+503", flag: "SV", iso: "SV" },
  { name: "Honduras", code: "+504", flag: "HN", iso: "HN" },
  { name: "Nicaragua", code: "+505", flag: "NI", iso: "NI" },
  { name: "Costa Rica", code: "+506", flag: "CR", iso: "CR" },
  { name: "Panama", code: "+507", flag: "PA", iso: "PA" },
  { name: "Cuba", code: "+53", flag: "CU", iso: "CU" },
  { name: "Jamaica", code: "+1876", flag: "JM", iso: "JM" },
  { name: "Haiti", code: "+509", flag: "HT", iso: "HT" },
  { name: "Dominican Republic", code: "+1809", flag: "DO", iso: "DO" },
  { name: "Saudi Arabia", code: "+966", flag: "SA", iso: "SA" },
  { name: "United Arab Emirates", code: "+971", flag: "AE", iso: "AE" },
  { name: "Qatar", code: "+974", flag: "QA", iso: "QA" },
  { name: "Kuwait", code: "+965", flag: "KW", iso: "KW" },
  { name: "Bahrain", code: "+973", flag: "BH", iso: "BH" },
  { name: "Oman", code: "+968", flag: "OM", iso: "OM" },
  { name: "Yemen", code: "+967", flag: "YE", iso: "YE" },
  { name: "Iraq", code: "+964", flag: "IQ", iso: "IQ" },
  { name: "Jordan", code: "+962", flag: "JO", iso: "JO" },
  { name: "Lebanon", code: "+961", flag: "LB", iso: "LB" },
  { name: "Syria", code: "+963", flag: "SY", iso: "SY" },
  { name: "Palestine", code: "+970", flag: "PS", iso: "PS" },
  { name: "Turkey", code: "+90", flag: "TR", iso: "TR" },
  { name: "Iran", code: "+98", flag: "IR", iso: "IR" },
  { name: "Afghanistan", code: "+93", flag: "AF", iso: "AF" }
]

// Country names without flags for the main country selector
export const countriesListWithFlags = [
  { name: "Egypt", flag: "eg" },
  { name: "Afghanistan", flag: "af" },
  { name: "Albania", flag: "al" },
  { name: "Algeria", flag: "dz" },
  { name: "Andorra", flag: "ad" },
  { name: "Angola", flag: "ao" },
  { name: "Antigua and Barbuda", flag: "ag" },
  { name: "Argentina", flag: "ar" },
  { name: "Armenia", flag: "am" },
  { name: "Australia", flag: "au" },
  { name: "Austria", flag: "at" },
  { name: "Azerbaijan", flag: "az" },
  { name: "Bahamas", flag: "BS" },
  { name: "Bahrain", flag: "BH" },
  { name: "Bangladesh", flag: "BD" },
  { name: "Barbados", flag: "BB" },
  { name: "Belarus", flag: "BY" },
  { name: "Belgium", flag: "BE" },
  { name: "Belize", flag: "BZ" },
  { name: "Benin", flag: "BJ" },
  { name: "Bhutan", flag: "BT" },
  { name: "Bolivia", flag: "BO" },
  { name: "Bosnia and Herzegovina", flag: "BA" },
  { name: "Botswana", flag: "BW" },
  { name: "Brazil", flag: "BR" },
  { name: "Brunei", flag: "BN" },
  { name: "Bulgaria", flag: "BG" },
  { name: "Burkina Faso", flag: "BF" },
  { name: "Burundi", flag: "BI" },
  { name: "Cabo Verde", flag: "CV" },
  { name: "Cambodia", flag: "KH" },
  { name: "Cameroon", flag: "CM" },
  { name: "Canada", flag: "CA" },
  { name: "Central African Republic", flag: "CF" },
  { name: "Chad", flag: "TD" },
  { name: "Chile", flag: "CL" },
  { name: "China", flag: "CN" },
  { name: "Colombia", flag: "CO" },
  { name: "Comoros", flag: "KM" },
  { name: "Congo (Congo-Brazzaville)", flag: "CG" },
  { name: "Costa Rica", flag: "CR" },
  { name: "Croatia", flag: "HR" },
  { name: "Cuba", flag: "CU" },
  { name: "Cyprus", flag: "CY" },
  { name: "Czechia (Czech Republic)", flag: "CZ" },
  { name: "Democratic Republic of the Congo", flag: "CD" }, 
  { name: "Denmark", flag: "DK" },
  { name: "Djibouti", flag: "DJ" },
  { name: "Dominica", flag: "DM" },
  { name: "Dominican Republic", flag: "DO" },
  { name: "Ecuador", flag: "EC" },
  { name: "El Salvador", flag: "SV" },
  { name: "Equatorial Guinea", flag: "GQ" },
  { name: "Eritrea", flag: "ER" },
  { name: "Estonia", flag: "EE" },
  { name: "Eswatini (fmr. Swaziland)", flag: "SZ" },
  { name: "Ethiopia", flag: "ET" },
  { name: "Fiji", flag: "FJ" },
  { name: "Finland", flag: "FI" },
  { name: "France", flag: "FR" },
  { name: "Gabon", flag: "GA" },
  { name: "Gambia", flag: "GM" },
  { name: "Georgia", flag: "GE" },
  { name: "Germany", flag: "DE" },
  { name: "Ghana", flag: "GH" },
  { name: "Greece", flag: "GR" },
  { name: "Grenada", flag: "GD" },
  { name: "Guatemala", flag: "GT" },  
  { name: "Guinea", flag: "GN" },
  { name: "Guinea-Bissau", flag: "GW" },
  { name: "Guyana", flag: "GY" },
  { name: "Haiti", flag: "HT" },
  { name: "Holy See", flag: "VA" },
  { name: "Honduras", flag: "HN" },
  { name: "Hungary", flag: "HU" },
  { name: "Iceland", flag: "IS" },
  { name: "India", flag: "IN" },
  { name: "Indonesia", flag: "ID" },
  { name: "Iran", flag: "IR" },
  { name: "Iraq", flag: "IQ" },
  { name: "Ireland", flag: "IE" },
  { name: "Italy", flag: "IT" },
  { name: "Jamaica", flag: "JM" },
  { name: "Japan", flag: "JP" },
  { name: "Jordan", flag: "JO" },
  { name: "Kazakhstan", flag: "KZ" },
  { name: "Kenya", flag: "KE" },
  { name: "Kiribati", flag: "KI" },
  { name: "Kuwait", flag: "KW" },
  { name: "Kyrgyzstan", flag: "KG" },
  { name: "Laos", flag: "LA" },
  { name: "Latvia", flag: "LV" },
  { name: "Lebanon", flag: "LB" },
  { name: "Lesotho", flag: "LS" },  
  { name: "Liberia", flag: "LR" },
  { name: "Libya", flag: "LY" },
  { name: "Liechtenstein", flag: "LI" },
  { name: "Lithuania", flag: "LT" },
  { name: "Luxembourg", flag: "LU" },
  { name: "Madagascar", flag: "MG" },
  { name: "Malawi", flag: "MW" },
  { name: "Malaysia", flag: "MY" },
  { name: "Maldives", flag: "MV" },
  { name: "Mali", flag: "ML" },     
  { name: "Malta", flag: "MT" },
  { name: "Marshall Islands", flag: "MH" },
  { name: "Mauritania", flag: "MR" },
  { name: "Mauritius", flag: "MU" },
  { name: "Mexico", flag: "MX" },
  { name: "Micronesia", flag: "FM" },
  { name: "Moldova", flag: "MD" },
  { name: "Monaco", flag: "MC" },
  { name: "Mongolia", flag: "MN" },
  { name: "Montenegro", flag: "ME" },
  { name: "Morocco", flag: "MA" },
  { name: "Mozambique", flag: "MZ" },
  { name: "Myanmar (Burma)", flag: "MM" },
  { name: "Namibia", flag: "NA" },
  { name: "Nauru", flag: "NR" },
  { name: "Nepal", flag: "NP" },
  { name: "Netherlands", flag: "NL" },
  { name: "New Zealand", flag: "NZ" },
  { name: "Nicaragua", flag: "NI" },
  { name: "Niger", flag: "NE" },
  { name: "Nigeria", flag: "NG" },
  { name: "North Korea", flag: "KP" },
  { name: "North Macedonia", flag: "MK" },
  { name: "Norway", flag: "NO" },
  { name: "Oman", flag: "OM" },
  { name: "Pakistan", flag: "PK" },
  { name: "Palau", flag: "PW" },
  { name: "Palestine State", flag: "PS" },
  { name: "Panama", flag: "PA" },
  { name: "Papua New Guinea", flag: "PG" },
  { name: "Paraguay", flag: "PY" },
  { name: "Peru", flag: "PE" },
  { name: "Philippines", flag: "PH" },
  { name: "Poland", flag: "PL" },
  { name: "Portugal", flag: "PT" }, 
  { name: "Qatar", flag: "QA" },
  { name: "Romania", flag: "RO" },
  { name: "Russia", flag: "RU" },
  { name: "Rwanda", flag: "RW" },
  { name: "Saint Kitts and Nevis", flag: "KN" },
  { name: "Saint Lucia", flag: "LC" },
  { name: "Saint Vincent and the Grenadines", flag: "VC" },
  { name: "Samoa", flag: "WS" },
  { name: "San Marino", flag: "SM" },
  { name: "Sao Tome and Principe", flag: "ST" },
  { name: "Saudi Arabia", flag: "SA" },
  { name: "Senegal", flag: "SN" },
  { name: "Serbia", flag: "RS" },
  { name: "Seychelles", flag: "SC" },
  { name: "Sierra Leone", flag: "SL" },
  { name: "Singapore", flag: "SG" },
  { name: "Slovakia", flag: "SK" },
  { name: "Slovenia", flag: "SI" },
  { name: "Solomon Islands", flag: "SB" },
  { name: "Somalia", flag: "SO" },
  { name: "South Africa", flag: "ZA" },
  { name: "South Korea", flag: "KR" },
  { name: "South Sudan", flag: "SS" },
  { name: "Spain", flag: "ES" },
  { name: "Sri Lanka", flag: "LK" },
  { name: "Sudan", flag: "SD" },
  { name: "Suriname", flag: "SR" },
  { name: "Sweden", flag: "SE" },
  { name: "Switzerland", flag: "CH" },
  { name: "Syria", flag: "SY" },
  { name: "Tajikistan", flag: "TJ" },
  { name: "Tanzania", flag: "TZ" },
  { name: "Thailand", flag: "TH" },
  { name: "Timor-Leste", flag: "TL" },
  { name: "Togo", flag: "TG" },
  { name: "Tonga", flag: "TO" },
  { name: "Trinidad and Tobago", flag: "TT" },
  { name: "Tunisia", flag: "TN" },
  { name: "Turkey", flag: "TR" },
  { name: "Turkmenistan", flag: "TM" },
  { name: "Tuvalu", flag: "TV" },
  { name: "Uganda", flag: "UG" },
  { name: "Ukraine", flag: "UA" },
  { name: "United Arab Emirates", flag: "AE" },
  { name: "United Kingdom", flag: "GB" },
  { name: "United States of America", flag: "US" },
  { name: "Uruguay", flag: "UY" },
  { name: "Uzbekistan", flag: "UZ" },
  { name: "Vanuatu", flag: "VU" },
  { name: "Venezuela", flag: "VE" },
  { name: "Vietnam", flag: "VN" },
  { name: "Yemen", flag: "YE" },
  { name: "Zambia", flag: "ZM" },
  { name: "Zimbabwe", flag: "ZW" }
]

// Phone number validation patterns by country
export const phoneValidationPatterns = {
  "+20": { pattern: /^[1-9]\d{8,9}$/, example: "1012345678", minLength: 9, maxLength: 10 }, // Egypt
  "+1": { pattern: /^[2-9]\d{9}$/, example: "2025551234", minLength: 10, maxLength: 10 }, // US/Canada
  "+44": { pattern: /^[1-9]\d{9,10}$/, example: "2071234567", minLength: 10, maxLength: 11 }, // UK
  "+33": { pattern: /^[1-9]\d{8}$/, example: "123456789", minLength: 9, maxLength: 9 }, // France
  "+49": { pattern: /^[1-9]\d{10,11}$/, example: "15712345678", minLength: 11, maxLength: 12 }, // Germany
  "+39": { pattern: /^[1-9]\d{8,9}$/, example: "123456789", minLength: 9, maxLength: 10 }, // Italy
  "+34": { pattern: /^[6-9]\d{8}$/, example: "612345678", minLength: 9, maxLength: 9 }, // Spain
  "+91": { pattern: /^[6-9]\d{9}$/, example: "9876543210", minLength: 10, maxLength: 10 }, // India
  "+86": { pattern: /^1[3-9]\d{9}$/, example: "13812345678", minLength: 11, maxLength: 11 }, // China
  "+81": { pattern: /^[7-9]\d{9}$/, example: "9012345678", minLength: 10, maxLength: 10 }, // Japan
  "+82": { pattern: /^1[0-9]\d{8}$/, example: "1012345678", minLength: 10, maxLength: 10 }, // South Korea
  "+966": { pattern: /^5\d{8}$/, example: "512345678", minLength: 9, maxLength: 9 }, // Saudi Arabia
  "+971": { pattern: /^5[0-9]\d{7}$/, example: "501234567", minLength: 9, maxLength: 9 }, // UAE
  // Add more patterns as needed
}

export const validatePhoneNumber = (countryCode, phoneNumber) => {
  const pattern = phoneValidationPatterns[countryCode]
  if (!pattern) {
    // Generic validation for countries without specific patterns
    return {
      isValid: /^\d{7,15}$/.test(phoneNumber),
      error: phoneNumber.length < 7 ? "Phone number too short" : 
             phoneNumber.length > 15 ? "Phone number too long" : 
             "Invalid phone number format"
    }
  }
  
  const isValid = pattern.pattern.test(phoneNumber)
  let error = ""
  
  if (!isValid) {
    if (phoneNumber.length < pattern.minLength) {
      error = `Phone number too short (minimum ${pattern.minLength} digits)`
    } else if (phoneNumber.length > pattern.maxLength) {
      error = `Phone number too long (maximum ${pattern.maxLength} digits)`
    } else {
      error = `Invalid format. Example: ${countryCode}${pattern.example}`
    }
  }
  
  return { isValid, error }
}
