export const countriesWithFlags = [
  { name: "Egypt", code: "+20", flag: "🇪🇬", iso: "EG" },
  { name: "United States", code: "+1", flag: "🇺🇸", iso: "US" },
  { name: "Canada", code: "+1", flag: "🇨🇦", iso: "CA" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧", iso: "GB" },
  { name: "France", code: "+33", flag: "🇫🇷", iso: "FR" },
  { name: "Germany", code: "+49", flag: "🇩🇪", iso: "DE" },
  { name: "Italy", code: "+39", flag: "🇮🇹", iso: "IT" },
  { name: "Spain", code: "+34", flag: "🇪🇸", iso: "ES" },
  { name: "Netherlands", code: "+31", flag: "🇳🇱", iso: "NL" },
  { name: "Belgium", code: "+32", flag: "🇧🇪", iso: "BE" },
  { name: "Switzerland", code: "+41", flag: "🇨🇭", iso: "CH" },
  { name: "Austria", code: "+43", flag: "🇦🇹", iso: "AT" },
  { name: "Denmark", code: "+45", flag: "🇩🇰", iso: "DK" },
  { name: "Sweden", code: "+46", flag: "🇸🇪", iso: "SE" },
  { name: "Norway", code: "+47", flag: "🇳🇴", iso: "NO" },
  { name: "Finland", code: "+358", flag: "🇫🇮", iso: "FI" },
  { name: "Poland", code: "+48", flag: "🇵🇱", iso: "PL" },
  { name: "Czech Republic", code: "+420", flag: "🇨🇿", iso: "CZ" },
  { name: "Slovakia", code: "+421", flag: "🇸🇰", iso: "SK" },
  { name: "Hungary", code: "+36", flag: "🇭🇺", iso: "HU" },
  { name: "Romania", code: "+40", flag: "🇷🇴", iso: "RO" },
  { name: "Bulgaria", code: "+359", flag: "🇧🇬", iso: "BG" },
  { name: "Greece", code: "+30", flag: "🇬🇷", iso: "GR" },
  { name: "Portugal", code: "+351", flag: "🇵🇹", iso: "PT" },
  { name: "Ireland", code: "+353", flag: "🇮🇪", iso: "IE" },
  { name: "Russia", code: "+7", flag: "🇷🇺", iso: "RU" },
  { name: "China", code: "+86", flag: "🇨🇳", iso: "CN" },
  { name: "Japan", code: "+81", flag: "🇯🇵", iso: "JP" },
  { name: "South Korea", code: "+82", flag: "🇰🇷", iso: "KR" },
  { name: "India", code: "+91", flag: "🇮🇳", iso: "IN" },
  { name: "Pakistan", code: "+92", flag: "🇵🇰", iso: "PK" },
  { name: "Bangladesh", code: "+880", flag: "🇧🇩", iso: "BD" },
  { name: "Sri Lanka", code: "+94", flag: "🇱🇰", iso: "LK" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾", iso: "MY" },
  { name: "Singapore", code: "+65", flag: "🇸🇬", iso: "SG" },
  { name: "Thailand", code: "+66", flag: "🇹🇭", iso: "TH" },
  { name: "Vietnam", code: "+84", flag: "🇻🇳", iso: "VN" },
  { name: "Philippines", code: "+63", flag: "🇵🇭", iso: "PH" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩", iso: "ID" },
  { name: "Australia", code: "+61", flag: "🇦🇺", iso: "AU" },
  { name: "New Zealand", code: "+64", flag: "🇳🇿", iso: "NZ" },
  { name: "South Africa", code: "+27", flag: "🇿🇦", iso: "ZA" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬", iso: "NG" },
  { name: "Kenya", code: "+254", flag: "🇰🇪", iso: "KE" },
  { name: "Ghana", code: "+233", flag: "🇬🇭", iso: "GH" },
  { name: "Morocco", code: "+212", flag: "🇲🇦", iso: "MA" },
  { name: "Algeria", code: "+213", flag: "🇩🇿", iso: "DZ" },
  { name: "Tunisia", code: "+216", flag: "🇹🇳", iso: "TN" },
  { name: "Libya", code: "+218", flag: "🇱🇾", iso: "LY" },
  { name: "Sudan", code: "+249", flag: "🇸🇩", iso: "SD" },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹", iso: "ET" },
  { name: "Uganda", code: "+256", flag: "🇺🇬", iso: "UG" },
  { name: "Tanzania", code: "+255", flag: "🇹🇿", iso: "TZ" },
  { name: "Zambia", code: "+260", flag: "🇿🇲", iso: "ZM" },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼", iso: "ZW" },
  { name: "Botswana", code: "+267", flag: "🇧🇼", iso: "BW" },
  { name: "Namibia", code: "+264", flag: "🇳🇦", iso: "NA" },
  { name: "Argentina", code: "+54", flag: "🇦🇷", iso: "AR" },
  { name: "Brazil", code: "+55", flag: "🇧🇷", iso: "BR" },
  { name: "Chile", code: "+56", flag: "🇨🇱", iso: "CL" },
  { name: "Colombia", code: "+57", flag: "🇨🇴", iso: "CO" },
  { name: "Venezuela", code: "+58", flag: "🇻🇪", iso: "VE" },
  { name: "Peru", code: "+51", flag: "🇵🇪", iso: "PE" },
  { name: "Ecuador", code: "+593", flag: "🇪🇨", iso: "EC" },
  { name: "Bolivia", code: "+591", flag: "🇧🇴", iso: "BO" },
  { name: "Paraguay", code: "+595", flag: "🇵🇾", iso: "PY" },
  { name: "Uruguay", code: "+598", flag: "🇺🇾", iso: "UY" },
  { name: "Mexico", code: "+52", flag: "🇲🇽", iso: "MX" },
  { name: "Guatemala", code: "+502", flag: "🇬🇹", iso: "GT" },
  { name: "El Salvador", code: "+503", flag: "🇸🇻", iso: "SV" },
  { name: "Honduras", code: "+504", flag: "🇭🇳", iso: "HN" },
  { name: "Nicaragua", code: "+505", flag: "🇳🇮", iso: "NI" },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷", iso: "CR" },
  { name: "Panama", code: "+507", flag: "🇵🇦", iso: "PA" },
  { name: "Cuba", code: "+53", flag: "🇨🇺", iso: "CU" },
  { name: "Jamaica", code: "+1876", flag: "🇯🇲", iso: "JM" },
  { name: "Haiti", code: "+509", flag: "🇭🇹", iso: "HT" },
  { name: "Dominican Republic", code: "+1809", flag: "🇩🇴", iso: "DO" },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦", iso: "SA" },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪", iso: "AE" },
  { name: "Qatar", code: "+974", flag: "🇶🇦", iso: "QA" },
  { name: "Kuwait", code: "+965", flag: "🇰🇼", iso: "KW" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭", iso: "BH" },
  { name: "Oman", code: "+968", flag: "🇴🇲", iso: "OM" },
  { name: "Yemen", code: "+967", flag: "🇾🇪", iso: "YE" },
  { name: "Iraq", code: "+964", flag: "🇮🇶", iso: "IQ" },
  { name: "Jordan", code: "+962", flag: "🇯🇴", iso: "JO" },
  { name: "Lebanon", code: "+961", flag: "🇱🇧", iso: "LB" },
  { name: "Syria", code: "+963", flag: "🇸🇾", iso: "SY" },
  { name: "Israel", code: "+972", flag: "🇮🇱", iso: "IL" },
  { name: "Palestine", code: "+970", flag: "🇵🇸", iso: "PS" },
  { name: "Turkey", code: "+90", flag: "🇹🇷", iso: "TR" },
  { name: "Iran", code: "+98", flag: "🇮🇷", iso: "IR" },
  { name: "Afghanistan", code: "+93", flag: "🇦🇫", iso: "AF" }
]

// Country names without flags for the main country selector
export const countriesListWithFlags = [
  { name: "Egypt", flag: "🇪🇬" },
  { name: "Afghanistan", flag: "🇦🇫" },
  { name: "Albania", flag: "🇦🇱" },
  { name: "Algeria", flag: "🇩🇿" },
  { name: "Andorra", flag: "🇦🇩" },
  { name: "Angola", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", flag: "🇦🇬" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Armenia", flag: "🇦🇲" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Azerbaijan", flag: "🇦🇿" },
  { name: "Bahamas", flag: "🇧🇸" },
  { name: "Bahrain", flag: "🇧🇭" },
  { name: "Bangladesh", flag: "🇧🇩" },
  { name: "Barbados", flag: "🇧🇧" },
  { name: "Belarus", flag: "🇧🇾" },
  { name: "Belgium", flag: "🇧🇪" },
  { name: "Belize", flag: "🇧🇿" },
  { name: "Benin", flag: "🇧🇯" },
  { name: "Bhutan", flag: "🇧🇹" },
  { name: "Bolivia", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { name: "Botswana", flag: "🇧🇼" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "Brunei", flag: "🇧🇳" },
  { name: "Bulgaria", flag: "🇧🇬" },
  { name: "Burkina Faso", flag: "🇧🇫" },
  { name: "Burundi", flag: "🇧🇮" },
  { name: "Cabo Verde", flag: "🇨🇻" },
  { name: "Cambodia", flag: "🇰🇭" },
  { name: "Cameroon", flag: "🇨🇲" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Central African Republic", flag: "🇨🇫" },
  { name: "Chad", flag: "🇹🇩" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "China", flag: "🇨🇳" },
  { name: "Colombia", flag: "🇨🇴" },
  { name: "Comoros", flag: "🇰🇲" },
  { name: "Congo (Congo-Brazzaville)", flag: "🇨🇬" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Croatia", flag: "🇭🇷" },
  { name: "Cuba", flag: "🇨🇺" },
  { name: "Cyprus", flag: "🇨🇾" },
  { name: "Czechia (Czech Republic)", flag: "🇨🇿" },
  { name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { name: "Denmark", flag: "🇩🇰" },
  { name: "Djibouti", flag: "🇩🇯" },
  { name: "Dominica", flag: "🇩🇲" },
  { name: "Dominican Republic", flag: "🇩🇴" },
  { name: "Ecuador", flag: "🇪🇨" },
  { name: "El Salvador", flag: "🇸🇻" },
  { name: "Equatorial Guinea", flag: "🇬🇶" },
  { name: "Eritrea", flag: "🇪🇷" },
  { name: "Estonia", flag: "🇪🇪" },
  { name: "Eswatini (fmr. Swaziland)", flag: "🇸🇿" },
  { name: "Ethiopia", flag: "🇪🇹" },
  { name: "Fiji", flag: "🇫🇯" },
  { name: "Finland", flag: "🇫🇮" },
  { name: "France", flag: "🇫🇷" },
  { name: "Gabon", flag: "🇬🇦" },
  { name: "Gambia", flag: "🇬🇲" },
  { name: "Georgia", flag: "🇬🇪" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Greece", flag: "🇬🇷" },
  { name: "Grenada", flag: "🇬🇩" },
  { name: "Guatemala", flag: "🇬🇹" },
  { name: "Guinea", flag: "🇬🇳" },
  { name: "Guinea-Bissau", flag: "🇬🇼" },
  { name: "Guyana", flag: "🇬🇾" },
  { name: "Haiti", flag: "🇭🇹" },
  { name: "Holy See", flag: "🇻🇦" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "Hungary", flag: "🇭🇺" },
  { name: "Iceland", flag: "🇮🇸" },
  { name: "India", flag: "🇮🇳" },
  { name: "Indonesia", flag: "🇮🇩" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Iraq", flag: "🇮🇶" },
  { name: "Ireland", flag: "🇮🇪" },
  { name: "Israel", flag: "🇮🇱" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Jamaica", flag: "🇯🇲" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Jordan", flag: "🇯🇴" },
  { name: "Kazakhstan", flag: "🇰🇿" },
  { name: "Kenya", flag: "🇰🇪" },
  { name: "Kiribati", flag: "🇰🇮" },
  { name: "Kuwait", flag: "🇰🇼" },
  { name: "Kyrgyzstan", flag: "🇰🇬" },
  { name: "Laos", flag: "🇱🇦" },
  { name: "Latvia", flag: "🇱🇻" },
  { name: "Lebanon", flag: "🇱🇧" },
  { name: "Lesotho", flag: "🇱🇸" },
  { name: "Liberia", flag: "🇱🇷" },
  { name: "Libya", flag: "🇱🇾" },
  { name: "Liechtenstein", flag: "🇱🇮" },
  { name: "Lithuania", flag: "🇱🇹" },
  { name: "Luxembourg", flag: "🇱🇺" },
  { name: "Madagascar", flag: "🇲🇬" },
  { name: "Malawi", flag: "🇲🇼" },
  { name: "Malaysia", flag: "🇲🇾" },
  { name: "Maldives", flag: "🇲🇻" },
  { name: "Mali", flag: "🇲🇱" },
  { name: "Malta", flag: "🇲🇹" },
  { name: "Marshall Islands", flag: "🇲🇭" },
  { name: "Mauritania", flag: "🇲🇷" },
  { name: "Mauritius", flag: "🇲🇺" },
  { name: "Mexico", flag: "🇲🇽" },
  { name: "Micronesia", flag: "🇫🇲" },
  { name: "Moldova", flag: "🇲🇩" },
  { name: "Monaco", flag: "🇲🇨" },
  { name: "Mongolia", flag: "🇲🇳" },
  { name: "Montenegro", flag: "🇲🇪" },
  { name: "Morocco", flag: "🇲🇦" },
  { name: "Mozambique", flag: "🇲🇿" },
  { name: "Myanmar (Burma)", flag: "🇲🇲" },
  { name: "Namibia", flag: "🇳🇦" },
  { name: "Nauru", flag: "🇳🇷" },
  { name: "Nepal", flag: "🇳🇵" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "New Zealand", flag: "🇳🇿" },
  { name: "Nicaragua", flag: "🇳🇮" },
  { name: "Niger", flag: "🇳🇪" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "North Korea", flag: "🇰🇵" },
  { name: "North Macedonia", flag: "🇲🇰" },
  { name: "Norway", flag: "🇳🇴" },
  { name: "Oman", flag: "🇴🇲" },
  { name: "Pakistan", flag: "🇵🇰" },
  { name: "Palau", flag: "🇵🇼" },
  { name: "Palestine State", flag: "🇵🇸" },
  { name: "Panama", flag: "🇵🇦" },
  { name: "Papua New Guinea", flag: "🇵🇬" },
  { name: "Paraguay", flag: "🇵🇾" },
  { name: "Peru", flag: "🇵🇪" },
  { name: "Philippines", flag: "🇵🇭" },
  { name: "Poland", flag: "🇵🇱" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "Romania", flag: "🇷🇴" },
  { name: "Russia", flag: "🇷🇺" },
  { name: "Rwanda", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { name: "Saint Lucia", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { name: "Samoa", flag: "🇼🇸" },
  { name: "San Marino", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", flag: "🇸🇹" },
  { name: "Saudi Arabia", flag: "🇸🇦" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Serbia", flag: "🇷🇸" },
  { name: "Seychelles", flag: "🇸🇨" },
  { name: "Sierra Leone", flag: "🇸🇱" },
  { name: "Singapore", flag: "🇸🇬" },
  { name: "Slovakia", flag: "🇸🇰" },
  { name: "Slovenia", flag: "🇸🇮" },
  { name: "Solomon Islands", flag: "🇸🇧" },
  { name: "Somalia", flag: "🇸🇴" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "South Korea", flag: "🇰🇷" },
  { name: "South Sudan", flag: "🇸🇸" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Sri Lanka", flag: "🇱🇰" },
  { name: "Sudan", flag: "🇸🇩" },
  { name: "Suriname", flag: "🇸🇷" },
  { name: "Sweden", flag: "🇸🇪" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "Syria", flag: "🇸🇾" },
  { name: "Tajikistan", flag: "🇹🇯" },
  { name: "Tanzania", flag: "🇹🇿" },
  { name: "Thailand", flag: "🇹🇭" },
  { name: "Timor-Leste", flag: "🇹🇱" },
  { name: "Togo", flag: "🇹🇬" },
  { name: "Tonga", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", flag: "🇹🇹" },
  { name: "Tunisia", flag: "🇹🇳" },
  { name: "Turkey", flag: "🇹🇷" },
  { name: "Turkmenistan", flag: "🇹🇲" },
  { name: "Tuvalu", flag: "🇹🇻" },
  { name: "Uganda", flag: "🇺🇬" },
  { name: "Ukraine", flag: "🇺🇦" },
  { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "United States of America", flag: "🇺🇸" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "Uzbekistan", flag: "🇺🇿" },
  { name: "Vanuatu", flag: "🇻🇺" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "Vietnam", flag: "🇻🇳" },
  { name: "Yemen", flag: "🇾🇪" },
  { name: "Zambia", flag: "🇿🇲" },
  { name: "Zimbabwe", flag: "🇿🇼" }
]

// Phone number validation patterns by country
export const phoneValidationPatterns = {
  "+20": { pattern: /^[1-9]\d{8,9}$/, example: "1012345678", minLength: 9, maxLength: 10 }, // Egypt
  "+1": { pattern: /^[2-9]\d{9}$/, example: "2025551234", minLength: 10, maxLength: 10 }, // US/Canada
  "+44": { pattern: /^[1-9]\d{9,10}$/, example: "2071234567", minLength: 10, maxLength: 11 }, // UK
  "+33": { pattern: /^[1-9]\d{8}$/, example: "123456789", minLength: 9, maxLength: 9 }, // France
  "+49": { pattern: /^[1-9]\d{10,11}$/, example: "15712345678", minLength: 11, maxLength: 12 }, // Germany
  "+39": { pattern: /^[1-9]\d{8,9}$/, example: "123456789", minLength: 9, maxLength: 10 }, // Italy
  "+34": { pattern: /^[6-9]\d{8}$/, example: "612345678", minLength: 9, maxLength: 9 }, // Spain
  "+91": { pattern: /^[6-9]\d{9}$/, example: "9876543210", minLength: 10, maxLength: 10 }, // India
  "+86": { pattern: /^1[3-9]\d{9}$/, example: "13812345678", minLength: 11, maxLength: 11 }, // China
  "+81": { pattern: /^[7-9]\d{9}$/, example: "9012345678", minLength: 10, maxLength: 10 }, // Japan
  "+82": { pattern: /^1[0-9]\d{8}$/, example: "1012345678", minLength: 10, maxLength: 10 }, // South Korea
  "+966": { pattern: /^5\d{8}$/, example: "512345678", minLength: 9, maxLength: 9 }, // Saudi Arabia
  "+971": { pattern: /^5[0-9]\d{7}$/, example: "501234567", minLength: 9, maxLength: 9 }, // UAE
  // Add more patterns as needed
}

export const validatePhoneNumber = (countryCode, phoneNumber) => {
  const pattern = phoneValidationPatterns[countryCode]
  if (!pattern) {
    // Generic validation for countries without specific patterns
    return {
      isValid: /^\d{7,15}$/.test(phoneNumber),
      error: phoneNumber.length < 7 ? "Phone number too short" : 
             phoneNumber.length > 15 ? "Phone number too long" : 
             "Invalid phone number format"
    }
  }
  
  const isValid = pattern.pattern.test(phoneNumber)
  let error = ""
  
  if (!isValid) {
    if (phoneNumber.length < pattern.minLength) {
      error = `Phone number too short (minimum ${pattern.minLength} digits)`
    } else if (phoneNumber.length > pattern.maxLength) {
      error = `Phone number too long (maximum ${pattern.maxLength} digits)`
    } else {
      error = `Invalid format. Example: ${countryCode}${pattern.example}`
    }
  }
  
  return { isValid, error }
}
